config/routes.rb
Gmi::Application.routes.draw do
  root :to => 'holding#index'
  match 'email', :to => 'holding#process_email', :as => :email

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /^$|^\S+\@(\[?)[a-zA-Z0-9\-\.]+\.([a-zA-Z]{2,4}|[0-9]{1,4})(\]?)$/ix
  attribute :subject,   :validate => true
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true
  
  OFFICE_EMAIL = 'gmioffice@me.com'
  DEVELOPER_EMAIL = 'foliosus@foliosus.com'
  
  def headers
    { :subject => "[GMI] #{subject}",
      :to => Rails.env.dev? ? DEVELOPER_EMAIL : OFFICE_EMAIL,
      :respond_to => %("#{name} <#{email}"),
      :from => OFFICE_EMAIL }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/holding_controller.rb
class HoldingController < ApplicationController
  caches_page :index
  
  def index
    @contact_form = ContactForm.new
  end
  
  def process_email
    @contact_form = ContactForm.new(params[:contact_form])
    respond_to do |format|
      format.html do
        @contact_form.deliver if @contact_form.valid?
        render :action => :index
      end
      format.js do
        if @contact_form.valid?
          @contact_form.deliver
          render :text => '<p class="response">Thanks for the message! We\'ll be in touch soon.</p>'
        else
          render :partial => 'email_form', :layout => false, :status => :ok
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holding_helper.rb
module HoldingHelper
end

app/views/holding/_email_form.html.haml
= form_for :contact_form, :url => email_path, :remote => true do |f|
  - if @contact_form.errors.any?
    %ul.errors
      - @contact_form.errors.full_messages.each do |msg|
        %li= h(msg)
  
  %label{:for => 'contact_email[name]'} Your name
  = f.text_field :name
  = f.text_field :nickname, :class => 'nickname'
  %label{:for => 'contact_email[email]'} Your email
  = f.text_field :email
  %label{:for => 'contact_email[subject]'} Subject
  = f.text_field :subject
  %label{:for => 'contact_email[message]'} Message
  = f.text_area :message
  = f.button 'Send it!'

app/views/holding/index.html.haml
.row.center
  .twelvecol
    %p= image_tag('logo_large.png', :width => 499, :height => 230, :class => 'center')
    %h1 Coming soon to downtown Greenville, SC

.row.center
  .twelvecol
    %p Projected start date: September, 2013
  .fourcol
  .fourcol
    %p
      %a.button{:href => 'javascript:void(0);'} Get in touch!
    #contact_information
      %h3 Telephone
      %p Reach us by phone at 571.439.5901.
      %h3 Email
      #contact_form
        = render :partial => "email_form"

.row.center
  .twelvecol
    %p.center#ami_logo
      %a{:href => 'http://www.montessori-ami.org/', :class => 'image'}= image_tag('logo_ami.jpg', :width => 92)
  
  .fourcol.last
  

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<title>Greenville Montessori Institute: Coming soon!</title>

		<meta name="viewport" content="width=device-width, initial-scale=1" />
    
  	<!--[if lte IE 9]><%= stylesheet_link_tag 'ie', :media => 'all' %><![endif]-->
  	
    <%= stylesheet_link_tag '1140', 'application', :media => "all" %>
    
    <link href='http://fonts.googleapis.com/css?family=Cabin:400,600,400italic,600italic' rel='stylesheet' type='text/css'>
    
    <%= javascript_include_tag 'application', 'css3-mediaqueries.js' %>
  	
    <%= csrf_meta_tags %>
    
		<!-- 
			This script enables structural HTML5 elements in old IE.
			http://code.google.com/p/html5shim/
		-->
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		
		<%- if Rails.env.production? -%>
  		<script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-31660071-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>
    <%- end -%>
	</head>

	<body lang="en">
	  
	  <div class="container">
		  <%= yield %>
    </div>

	</body>
</html>